const TWITTER_TOKENS = {
  TWITTER_CONSUMER_KEY: '9YxF4X3Y7sV9uNIF9AxDc05fL',
  TWITTER_CONSUMER_SECRET: 'Zc3s0SbCuYm2lE1yJnbvUAi0pEYajMiJizc35k0DiVJpPRnlIh',
  TWITTER_ACCESS_TOKEN: '366946763-YQ7pIMC9y397O6i9GmACYUAcSHSAdcb9Z0ajYNnh',
  TWITTER_ACCESS_TOKEN_SECRET: 'oX3O5eG2nUmh5Mzq6dlsQo9KHdbrseMNk33VhdZnyAfwX',
};

const SESSION = {
  COOKIE_KEY: 'thisappisawesome',
};

const ENV = process.env.NODE_ENV;

const SERVER_URL = 'http://localhost:5000';
// const SERVER_URL = 'http://13.233.63.57:5000/';

const SOCKET_URL = '127.0.0.1';

const SOCKET_PORT = 5001;

const JWT_SECRET = '3hmPDIfMO97zziRU';

const ERROR_CODES = {
  INVALID_SHAPE: 'INVALID_SHAPE',
  NOT_FOUND: 'NOT_FOUND',
  EXISTS: 'EXISTS',
  INVALID_AUTH: 'INVALID_AUTH',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
};

const KEYS = {
  ...TWITTER_TOKENS,
  ...SESSION,
  JWT_SECRET,
  ERROR_CODES,
  SERVER_URL,
  SOCKET_URL,
  SOCKET_PORT,
  ENV,
};

module.exports = KEYS;
